name: Build APK with Chaquopy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy==2.0.0 music21

      - name: Grant execute permission for gradlew
        run: |
          # Generate Gradle wrapper if it doesn't exist
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi
          chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SriMusic-APK
          path: app/build/outputs/apk/debug/app-debug.apk