name: Build APK with Chaquopy

on:
  push:
    branches: [ main, add-chaquopy-build-workflow ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip==21.3.1
          pip install kivy==2.0.0 music21==7.3.3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1

      - name: Download Gradle wrapper
        run: |
          mkdir -p gradle/wrapper
          wget -O gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v6.7.1/gradle/wrapper/gradle-wrapper.jar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --info --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SriMusic-APK
          path: app/build/outputs/apk/debug/app-debug.apk